package testcrud;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Iqbal Albana
 */
public class frmMain extends javax.swing.JFrame {

    String nol_jam;
    String nol_menit;
    String nol_detik;

    
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        selectData();
        setJam();
        setTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JK = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelWaktu = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNis = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdLaki = new javax.swing.JRadioButton();
        rdPerempuan = new javax.swing.JRadioButton();
        txtKelas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txtTempat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        BtnSave = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        BtnRefresh = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnEdit1 = new javax.swing.JButton();
        BtnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM BIODATA SISWA SMK TELKOM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 480, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("The Real Informatic School");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 50, 200, 30);

        labelWaktu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelWaktu.setText("Waktu");
        jPanel1.add(labelWaktu);
        labelWaktu.setBounds(760, 50, 170, 40);

        labelTanggal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTanggal.setText("Tanggal");
        jPanel1.add(labelTanggal);
        labelTanggal.setBounds(760, 10, 170, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 940, 100);

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("NIS");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 5, 50, 15);

        txtNis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNisActionPerformed(evt);
            }
        });
        jPanel2.add(txtNis);
        txtNis.setBounds(10, 20, 160, 30);

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel2.add(txtNama);
        txtNama.setBounds(10, 70, 230, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("JENIS KELAMIN");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 100, 100, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("NAMA");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 50, 50, 15);

        JK.add(rdLaki);
        rdLaki.setText("Laki-Laki");
        rdLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdLakiActionPerformed(evt);
            }
        });
        jPanel2.add(rdLaki);
        rdLaki.setBounds(10, 120, 110, 30);

        JK.add(rdPerempuan);
        rdPerempuan.setText("Perempuan");
        rdPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPerempuanActionPerformed(evt);
            }
        });
        jPanel2.add(rdPerempuan);
        rdPerempuan.setBounds(130, 120, 110, 30);

        txtKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKelasActionPerformed(evt);
            }
        });
        jPanel2.add(txtKelas);
        txtKelas.setBounds(10, 290, 230, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("KELAS");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 270, 50, 20);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail);
        txtEmail.setBounds(10, 340, 230, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("ALAMAT");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 370, 70, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("EMAIL");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 320, 50, 15);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 390, 230, 70);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("TEMPAT LAHIR");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 160, 100, 15);

        txtTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempatActionPerformed(evt);
            }
        });
        jPanel2.add(txtTempat);
        txtTempat.setBounds(10, 180, 230, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("TANGGAL LAHIR");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 220, 120, 15);
        jPanel2.add(txtTanggal);
        txtTanggal.setBounds(10, 240, 230, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 150, 250, 490);

        jPanel3.setBackground(new java.awt.Color(255, 255, 51));
        jPanel3.setLayout(null);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Jenis Kelamin", "Tempat Lahir", "Tanggal Lahir", "Kelas", "Email", "Alamat"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblData);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 660, 440);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(260, 170, 680, 470);

        jPanel4.setBackground(new java.awt.Color(255, 255, 51));
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ISIAN DATA SISWA");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 0, 190, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 110, 250, 30);

        jPanel5.setBackground(new java.awt.Color(255, 255, 51));
        jPanel5.setForeground(new java.awt.Color(153, 255, 153));
        jPanel5.setLayout(null);

        BtnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });
        jPanel5.add(BtnSave);
        BtnSave.setBounds(20, 10, 90, 30);

        BtnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });
        jPanel5.add(BtnClear);
        BtnClear.setBounds(240, 10, 90, 30);

        BtnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnRefresh.setText("Refresh");
        BtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefreshActionPerformed(evt);
            }
        });
        jPanel5.add(BtnRefresh);
        BtnRefresh.setBounds(350, 10, 90, 30);

        BtnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnDelete.setText("DELETE");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(BtnDelete);
        BtnDelete.setBounds(130, 10, 90, 30);

        BtnEdit1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnEdit1.setText("Print");
        BtnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEdit1ActionPerformed(evt);
            }
        });
        jPanel5.add(BtnEdit1);
        BtnEdit1.setBounds(570, 10, 90, 30);

        BtnPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnPrint.setText("Edit");
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        jPanel5.add(BtnPrint);
        BtnPrint.setBounds(460, 10, 90, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(260, 110, 680, 50);

        setSize(new java.awt.Dimension(955, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd/MM/yyyy");
        labelTanggal.setText("Tanggal " + kal.format(skrg));
    }
    
    public void setJam(){
        ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt. getSeconds();
                if (nilai_jam <= 9){
                     nol_jam = "0";
                }
                else{
                    nol_jam ="";
                }
                if (nilai_menit <= 9){
                     nol_menit = "0";
                }
                else{
                    nol_menit ="";
                }
                
                if (nilai_detik <= 9){
                     nol_detik = "0";
                }
                else{
                    nol_detik ="";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                labelWaktu.setText("Jam "+jam+":" + menit + ":"+ detik);
                
            }
        }; new Timer(100, taskPerformer).start();
    }
    
    private void txtNisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNisActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void rdPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdPerempuanActionPerformed

    private void txtKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelasActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(txtTanggal.getDate());
        
        if ("".equals(txtNis.getText())||"".equals(txtAlamat.getText())||"".equals(txtNama.getText())||"".equals(txtKelas.getText())||"".equals(txtEmail.getText())||"".equals(txtTempat.getText())||"".equals(tanggal)){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else{
         String JK = "";
         if(rdLaki.isSelected()){
             JK = "L";
         }
         else{
            JK = "P";
         }
         
         String SQL = "INSERT INTO t_siswa(NIS, NamaSiswa, JenisKelamin, TempatLahir, TanggalLahir, Kelas, Email, Alamat) " + "VALUES('"+txtNis.getText()+"','"+txtNama.getText()+"','"+JK+"','"+txtTempat.getText()+"','"+tanggal+"','"+txtKelas.getText()+"','"+txtEmail.getText()+"','"+txtAlamat.getText()+"')";
         int status = KoneksiDB.execute(SQL);
         if (status == 1){
             JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
             selectData();
         }
         else{
             JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
         }
        }
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        int baris = tblData.getSelectedRow();
        if (baris != -1){
            String NIS = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else{
                JOptionPane.showMessageDialog(this, "Data Gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris terlebih dahulu sebelum menghapus", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
      txtNama.setText("");
      txtNis.setText("");
      txtTempat.setText("");
      txtTanggal.setDate(null);
      txtKelas.setText("");
      txtEmail.setText("");
      txtAlamat.setText("");
      JK.clearSelection();
    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefreshActionPerformed
        selectData();
    }//GEN-LAST:event_BtnRefreshActionPerformed
    public void selectData() {
        String kolom[] = {"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel (null, kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()){
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String JenisKelamin = "";
                if ("L".equals(rs.getString(3))){
                    JenisKelamin = "Laki-Laki";
                } else {
                    JenisKelamin = "Perempuan";
                }
                String Kelas = rs.getString(4);
                String Email = rs.getString(4);
                String Alamat = rs.getString(4);
                String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
    } 
    
    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(txtTanggal.getDate());
        
        if ("".equals(txtNis.getText())||"".equals(txtAlamat.getText())||"".equals(txtNama.getText())||"".equals(txtKelas.getText())||"".equals(txtEmail.getText())||"".equals(txtTempat.getText())||"".equals(tanggal)){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else{
         String JK = "";
         if(rdLaki.isSelected()){
             JK = "L";
         }
         else{
            JK = "P";
         }
         
            String SQL = "UPDATE t_siswa SET "
                    + "NamaSiswa='"+txtNama.getText()+"',"
                    + "JenisKelamin='" + JK + "',"
                    + "TempatLahir='"+txtTempat.getText()+"',"
                    + "TanggalLahir='"+tanggal+"',"
                    + "Kelas='"+txtKelas.getText()+"',"
                    + "Email='" + txtEmail.getText() + "',"
                    + "Alamat='" + txtAlamat.getText()+"' "
                    + "WHERE NIS='"+txtNis.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris = tblData.getSelectedRow();
        if (baris !=1) {
            txtNis.setText(tblData.getValueAt(baris, 0).toString());
            txtNama.setText(tblData.getValueAt(baris, 1).toString());
            if ("Laki-Laki".equals(tblData.getValueAt(baris, 2).toString())){
                rdLaki.setSelected(true);
            } else {
                rdPerempuan.setSelected(true);
            }
            txtKelas.setText(tblData.getValueAt(baris, 3).toString());
            txtEmail.setText(tblData.getValueAt(baris, 4).toString());
            txtAlamat.setText(tblData.getValueAt(baris, 5).toString());
    }//GEN-LAST:event_tblDataMouseClicked

    private void txtTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempatActionPerformed

    }//GEN-LAST:event_txtTempatActionPerformed

    private void BtnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEdit1ActionPerformed
        MessageFormat header = new MessageFormat("Biodata Siswa SMK TELKOM MALANG");
       MessageFormat footer = new MessageFormat("Page {0,number,integer}");
       
       try {
           tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
       } catch (java.awt.print.PrinterException e) {
           System.err.format("Cannot Print %s&n", e.getMessage());
       }
    }//GEN-LAST:event_BtnEdit1ActionPerformed

    private void rdLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdLakiActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnEdit1;
    private javax.swing.JButton BtnPrint;
    private javax.swing.JButton BtnRefresh;
    private javax.swing.JButton BtnSave;
    private javax.swing.ButtonGroup JK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JLabel labelWaktu;
    private javax.swing.JRadioButton rdLaki;
    private javax.swing.JRadioButton rdPerempuan;
    private javax.swing.JTable tblData;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNis;
    private com.toedter.calendar.JDateChooser txtTanggal;
    private javax.swing.JTextField txtTempat;
    // End of variables declaration//GEN-END:variables

}
